# Generated by Django 3.2.23 on 2024-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_session_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_entry',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
